name: Django Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Config the environment
      run: |
        cp .env_example app/.env
    - name: Run migrations
      run: |
        python app/manage.py makemigrations
        python app/manage.py migrate
    - name: Run Tests
      run: |
        python app/manage.py test --failfast
    - name: Is Production Ready ?
      run: |
        python app/manage.py check --deploy
